services:

  # MySQL
  db:
    image: mysql:latest
    container_name: carsharing-mysql
    ports:
      - "3306:3306"
     env_file:
      - .env

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carsharing-phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env

  api:
    container_name: carsharing-api
    image: nginx:alpine
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carsharing
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  react:
    container_name: carsharing-react
    image: nginx:alpine
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
