services:

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carsharing
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: admin
    volumes:
      - db:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: superalex0102@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    container_name: carsharing-api
    build: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carsharing
    ports:
      - "8088:8080"
    depends_on:
      - db
    restart: unless-stopped

  react:
    container_name: carsharing-react
    image: node:latest
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    command: bash -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db:
  pgadmin_data: